# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pr: none
trigger:
  batch: true
  branches:
    include:
    - hotfix/*
    - release/*
    - feature/*
    - refs/tags/*
    - development

variables:
  solution: '**/CRM.sln'
  packages: './NuGet.Config'
  net: '5.0.100-rc.2.20479.15'
  project: '**/CRM.Server.csproj'

jobs:
- job: CI_Linux_Debug

  pool:
    vmImage: ubuntu-latest

  steps:
  - task: UseDotNet@2
    displayName: 'Download .NET 5.x SDK'
    inputs:
      packageType: 'sdk'
      version: '$(net)'
      includePreviewVersions: true
      performMultiLevelLookup: true
  - task: Npm@1
    displayName: 'NPM Install'
    inputs:
      command: 'install'
      workingDir: './Core/Libraries'
      verbose: true
  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      projects: '$(solution)'
      publishPackageMetadata: true
      nugetConfigPath: '$(packages)'
  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '$(project)'
      arguments: '--no-restore --configuration debug --runtime linux-x64'
